exclude: ^(blib2to3/|profiling/|tests/data/)
default_language_version:
  python: python3.8
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        description: "isort will sort python imports in a way that makes sense"
        entry: isort
        language: system
        types: [python]
        stages: [commit]
        args: # taken to comply with black
          - -rc
          - --lines=120
          - --use-parentheses
          - --trailing-comma
          - --multi-line=3

      - id: black
        name: black
        description: "black will standardize code style in all project files in-place"
        language: system
        entry: black
        types: [python]
        stages: [commit]
        args:
          - --line-length=120
